config/urls.py
# from django.contrib import admin
from django.urls import path, include


handler400 = 'adminlte_full.views.handler400'
handler403 = 'adminlte_full.views.handler403'
handler404 = 'adminlte_full.views.handler404'
handler500 = 'adminlte_full.views.handler500'


urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('adminlte_full.urls')),
    path('', include('core.urls')),
]

core/urls.py
from django.urls import path
# from django.urls import re_path, include
from . import views


urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    # re_path(r'^phone_login/', include('phone_login.urls', name='phone_login'),),
]

core/models.py
# from django.db import models

core/forms.py
from crispy_forms.bootstrap import AppendedText, PrependedText
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout
from django import forms
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext as _

from . import msgs

# Лэйблы
from .choices import SEX_CHOICES, REGION_CHOICES

ROLE_LABEL = _(u"Роль")
IDENTIFICATION_METHOD = _(u"Метод идентификации")

FIRST_NAME_LABEL = _(u"Ім")
LAST_NAME_LABEL = _(u"Фамилия")
MIDDLE_NAME_LABEL = _(u"Отчество")

# Вспомогательный текст

ROLE_HELP = _(u"")
IDENTIFICATION_HELP = _(
    u"С помощью номера договора или другого метода идентификации мы узнаем ваше "
    u"имя и предоставим всю нужную информацию")


class RoleForm(forms.Form):
    ROLE_CHOICES = (
        (0, 'Не выбрано'),
        (1, 'Клиент'),
        (2, 'Доктор'),
        (3, 'Фармацевт')
    )
    IDENTIFICATION_CHOICES = (
        (0, 'По номеру договора'),
        (1, 'По паспорту'),
        (2, 'По другому документу')
    )

    role = forms.ChoiceField(
        label=ROLE_LABEL,
        choices=ROLE_CHOICES,
        help_text="""Это поле сделано для теста, чтобы вы могли проверить как работают группы пользователей 
        в зависимости от роли, в будущем я думаю, что это вводить будет не нужно, а по номеру договора или другому 
        идентификатору мы будем определять группу пользователя."""
    )

    identification_method = forms.ChoiceField(
        label=IDENTIFICATION_METHOD,
        choices=IDENTIFICATION_CHOICES,
        help_text="""Это поле сейчас никак не работает, оно здесь стоит для примера, чтобы показать такую модель 
        взаимодействия с интерфейсом. Человек идентифицируется, например, по номеру договора и так определяется его роль
        и интерфейс, который он видит"""
    )

    @property
    def helper(self):
        helper = FormHelper()
        helper.form_show_labels = True
        helper.form_tag = False
        helper.layout = Layout(
            'role',
            'identification_method'
        )
        return helper

    def clean_role(self):
        """
        Проверка роли
        """

        role = self.cleaned_data.get('role')
        if role == '':
            raise forms.ValidationError(msgs.ROLE_ERROR)

        return role


class KostylForm(forms.Form):
    is_data_filled = forms.CharField()

    def helper(self):
        helper = FormHelper()
        helper.form_show_labels = True
        helper.form_tag = False
        helper.layout = Layout(
            AppendedText(
                'is_data_filled',
                mark_safe('<span class="fas fa-keyboard" id="is_data_filled"></span>'),
            )
        )
        return helper


class ModalWindowForm(forms.Form):
    """
    Персональные данные
    """
    first_name = forms.CharField(
        label='Ім\'я',
        max_length=50,
        required=True
    )
    last_name = forms.CharField(
        label='Прізвище',
        max_length=50,
        required=True
    )
    middle_name = forms.CharField(
        label='По батькові',
        max_length=50,
        required=True
    )
    email = forms.EmailField(
        label='Email',
        required=True
    )
    date_of_birth = forms.DateField(
        widget=forms.DateInput(
            attrs={'type': 'date'}
        ),
        label='Дата народження',
        help_text='Наприклад 18.01.1994',
        required=True,

    )
    sex = forms.ChoiceField(
        label='Стать',
        choices=SEX_CHOICES,
        required=True
    )
    region = forms.ChoiceField(
        label='Область',
        choices=REGION_CHOICES,
        required=True
    )
    city = forms.CharField(
        label='Місто',
        max_length=50,
        required=True
    )
    street = forms.CharField(
        label='Вулиця',
        max_length=50,
        required=True
    )
    house = forms.CharField(
        label='Дім',
        max_length=50,
        required=True
    )
    apartment = forms.CharField(
        label='Квартира',
        max_length=50,
        required=True

    )
    zip_code = forms.CharField(
        label='Індекс',
        max_length=50,
        required=True
    )
    series = forms.CharField(
        label='Серія',
        max_length=50,
        required=False,
        help_text='Якщо у вас паспорт зразка 1994 року'
    )
    number = forms.CharField(
        label='Номер',
        max_length=50,
        required=True,
        help_text='Для паспортів нового та старого зразку'
    )
    tax_number = forms.CharField(
        label='Налоговий номер',
        max_length=50,
        required=True,
        help_text='У паспортах нового зразку вказано як РНКОПП'
    )
    organization = forms.CharField(
        label='Установа',
        max_length=50,
        required=False
    )
    position = forms.CharField(
        label='Посада',
        max_length=50,
        required=False
    )

    @property
    def helper(self):
        helper = FormHelper()
        helper.form_show_labels = True
        helper.form_tag = False
        helper.layout = Layout(
            PrependedText('first_name',
                          '<input type="checkbox" checked="checked" value="" id="" name="first_name" '
                          'class="textinput textInput form-control-sm">',
                          active=True),
            'first_name',
            'last_name',
            'middle_name',
            'email',
            'date_of_birth',
            'sex',
            'region',
            'city',
            'street',
            'house',
            'apartment',
            'zip_code',
            'series',
            'number',
            'tax_number',
            'organization',
            'position',

        )
        return helper

core/views.py
from datetime import datetime, timedelta
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.urls import reverse
# from django.contrib import auth, messages
from django.shortcuts import render
# from django import forms
# from django.http import JsonResponse
# from django.urls import reverse_lazy
from django.views import View
from adminlte_base import MenuLoader, Message,  Dropdown
# from adminlte_base import MenuItem, Notification, Task, ThemeColor
from .forms import RoleForm, ModalWindowForm, KostylForm
from adminlte_full.adminlte import manager
from adminlte_full.models import MenuModel
from .utils import menu_deploy

User = get_user_model()


class IndexView(View):
    template_name = 'core/index.html'
    form_class = RoleForm
    form_class_modal_window = ModalWindowForm
    form_class_kostyl_form = KostylForm

    @method_decorator(login_required)
    def get(self, request):
        user = User.objects.get(phone=self.request.user)
        is_data_filled = '0'
        if user.role == 1:
            if not user.first_name or not user.last_name or not user.middle_name \
                    or not user.date_of_birth or not user.email or not user.region \
                    or not user.city or not user.street or not user.house\
                    or not user.zip_code or not user.number or not user.tax_number:
                is_data_filled = '1'

        form_modal_window = self.form_class_modal_window(
            initial={
                'first_name': user.first_name,
                'last_name': user.last_name,
                'middle_name': user.middle_name,
                'sex': user.sex,
                'email': user.email,
                'date_of_birth': user.date_of_birth,
                'region': user.region,
                'city': user.city,
                'street': user.street,
                'house': user.house,
                'apartment': user.apartment,
                'zip_code': user.zip_code,
                'series': user.series,
                'number': user.number,
                'tax_number': user.tax_number,
                'organization': user.organization,
                'position': user.position,
            })
        kostyl_form = self.form_class_kostyl_form(
            initial={
                'is_data_filled': is_data_filled
            }
        )
        try:
            MenuModel.objects.get(program_name='default_menu')
        except MenuModel.DoesNotExist:
            menu_deploy()

        return render(request, self.template_name, {'form': self.form_class,
                                                    'form_modal_window': form_modal_window,
                                                    'kostyl_form': kostyl_form})

    def post(self, request):
        form = self.form_class(request.POST)
        form_modal_window = self.form_class_modal_window(request.POST)
        if form.is_valid():
            phone = request.user.get_username()
            user = User.objects.get(phone=phone)
            user.role = form.cleaned_data['role']
            user.save()
            return HttpResponseRedirect(
                reverse('index')
            )
        if form_modal_window.is_valid():
            user = User.objects.get(phone=self.request.user.phone)
            user.first_name = form_modal_window.cleaned_data['first_name']
            user.last_name = form_modal_window.cleaned_data['last_name']
            user.middle_name = form_modal_window.cleaned_data['middle_name']
            user.email = form_modal_window.cleaned_data['email']
            user.sex = form_modal_window.cleaned_data['sex']
            user.date_of_birth = form_modal_window.cleaned_data['date_of_birth']
            user.region = form_modal_window.cleaned_data['region']
            user.city = form_modal_window.cleaned_data['city']
            user.street = form_modal_window.cleaned_data['street']
            user.house = form_modal_window.cleaned_data['house']
            user.apartment = form_modal_window.cleaned_data['apartment']
            user.zip_code = form_modal_window.cleaned_data['zip_code']
            user.series = form_modal_window.cleaned_data['series']
            user.number = form_modal_window.cleaned_data['number']
            user.tax_number = form_modal_window.cleaned_data['tax_number']
            user.organization = form_modal_window.cleaned_data['organization']
            user.position = form_modal_window.cleaned_data['position']
            user.save()
            return render(request, self.template_name, {'form': form, 'form_modal_window': form_modal_window})
        return render(request, self.template_name, {'form': form, 'form_modal_window': form_modal_window})


@manager.menu_loader
class MyMenuLoader(MenuLoader):
    def __call__(self, user):
        if user.is_superuser:
            return MenuModel.objects.get(program_name='admin_menu')
        if user.role == 1:
            # CUSTOMER
            return MenuModel.objects.get(program_name='customer_menu')
        if user.role == 2:
            # DOCTOR
            return MenuModel.objects.get(program_name='doctor_menu')
        if user.role == 3:
            # BUYER
            return MenuModel.objects.get(program_name='buyer_menu')
        return MenuModel.objects.get(program_name='default_menu')

    def sidebar_menu(self):
        menu = self._create(self(user=self.context['request'].user), active_path=self.context['request'].path)
        return menu


@manager.messages_loader
def load_messages(context):
    now = datetime.now()
    sender = context['user']
    messages = Dropdown('#', 15)
    messages.add(Message(sender, 'Тестовое сообщение 1', '#', sent_at=now - timedelta(seconds=16)), )

    return messages

core/templates/core/includes/modal_form_customuser.html
{% load crispy_forms_tags i18n %}

<form action="" method="post">
    {% csrf_token %}
    <div id="myModalBox" class="modal fade">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
              <!-- Заголовок модального окна -->
                <div class="modal-header">
                    <h6 class="modal-title">Будь ласка заповніть ваші дані щоб продовжити роботу</h6>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                </div>
                <!-- Основное содержимое модального окна -->
                <div class="modal-body">
                    <h5><b>Персональна Інформація</b></h5>
                    <div class="form-row">
                        <div class="form-group col-md-4 mb-0">
                            {{ form_modal_window.first_name|as_crispy_field }}
                            {{ form_modal_window.sex|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-4 mb-0">
                            {{ form_modal_window.last_name|as_crispy_field }}
                            {{ form_modal_window.date_of_birth|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-4 mb-0">
                            {{ form_modal_window.middle_name|as_crispy_field }}
                            {{ form_modal_window.email|as_crispy_field }}
                        </div>
                    </div>
                    <hr>
                    <h5><b>Адреса</b></h5>
                    <div class="form-row">
                        <div class="form-group col-md-4 mb-0">
                            {{ form_modal_window.zip_code|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-4 mb-0">
                            {{ form_modal_window.region|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-4 mb-0">
                            {{ form_modal_window.city|as_crispy_field }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-4 mb-0">
                            {{ form_modal_window.street|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-3 mb-0">
                            {{ form_modal_window.house|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-3 mb-0">
                            {{ form_modal_window.apartment|as_crispy_field }}
                        </div>
                    </div>
                    <hr>
                    <h5><b>Документи</b></h5>
                    <div class="form-row">
                        <div class="form-group col-md-4 mb-0">
                            {{ form_modal_window.number| as_crispy_field }}
                        </div>
                        <div class="form-group col-md-4 mb-0">
                           {{ form_modal_window.series| as_crispy_field }}
                        </div>
                        <div class="form-group col-md-4 mb-0">
                          {{ form_modal_window.tax_number| as_crispy_field }}
                        </div>
                    </div>
                    <hr>
                    <h5><b>Місце роботи</b></h5>
                    <div class="form-row">
                        <div class="form-group col-md-4 mb-0">
                            {{ form_modal_window.organization|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-4 mb-0">
                            {{ form_modal_window.position|as_crispy_field }}
                        </div>
                    </div>
                </div>
                <!-- Футер модального окна -->
                <div class="modal-footer">
                    <p>Я погоджуюся на обробку персональних даних.</p> <a href="">Угода користувача.</a>
                    <button type="submit" class="btn btn-primary btn-lg">{% trans 'Зберегти' %}</button>
                </div>
             </div>
        </div>
    </div>
</form>

<div class="modal hide" id="contactModal">
    {{ kostyl_form.is_data_filled }}
</div>

core/templates/core/includes/modal_form_script.html
<!-- Скрипт, вызывающий модальное окно после загрузки страницы -->
<script>
    $(document).ready(function() {
        $("#id_is_data_filled").hide();
        $(".asteriskField").hide();
        $(".form-control").addClass("form-control-sm");
        var is_data_filled = $("#id_is_data_filled").val();
        if (is_data_filled === '1') {
            $("#myModalBox").modal('show');
        }
    });
</script>

core/templates/core/includes/profile.html
<form class="well contact-form" method="post" action="/profile/edit/{{ item.id }}">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h3>Editing Profile</h3>
  </div>
  <div class="modal-body">
       {% csrf_token %}
{#       {{form.as_p}}#}
      {{form|crispy}}
  </div>
  <div class="modal-footer">
       <input class="btn btn-primary" type="submit" value="Save" />
       <input name="cancel" class="btn" type="submit" value="Cancel"/>
  </div>
</form>